import type { Column } from '@/features/rxsoft/types';
import type { ModelConfig } from '@/features/shared/model-schema';

const columns: Column[] = [
  {
    key: 'qcResult',
    label: 'QC Result',
    render: (row: any) => row.qcResult?.id ?? row.qcResultId ?? '-',
  },
  { key: 'rule', label: 'Rule' },
  { key: 'severity', label: 'Severity' },
  { key: 'description', label: 'Description' },
  { key: 'active', label: 'Active', render: (row: any) => (row.active ? 'Yes' : 'No') },
  { key: 'acknowledgedAt', label: 'Acknowledged At' },
];

export const qcAlertsConfig: ModelConfig = {
  id: 'qc-alerts',
  title: 'QC Alerts',
  description: 'Alerts generated by Westgard rule violations on QC results.',
  endpoint: '/lis/qc-alerts',
  columns,
  buildCreatePayload: (v) => v,
  buildUpdatePayload: (v) => v,
  canDelete: true,
};
