/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuestionnaireIndexRouteImport } from './routes/questionnaire/index'
import { Route as DamorexIndexRouteImport } from './routes/damorex/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedRoutingRouteRouteImport } from './routes/_authenticated/routing/route'
import { Route as AuthenticatedNotificationsRouteRouteImport } from './routes/_authenticated/notifications/route'
import { Route as AuthenticatedNotificationTemplatesRouteRouteImport } from './routes/_authenticated/notification-templates/route'
import { Route as AuthenticatedMessagesRouteRouteImport } from './routes/_authenticated/messages/route'
import { Route as AuthenticatedMessageTemplatesRouteRouteImport } from './routes/_authenticated/message-templates/route'
import { Route as AuthenticatedMessageLogsRouteRouteImport } from './routes/_authenticated/message-logs/route'
import { Route as AuthenticatedMappingRouteRouteImport } from './routes/_authenticated/mapping/route'
import { Route as AuthenticatedCommunicationChannelsRouteRouteImport } from './routes/_authenticated/communication-channels/route'
import { Route as AuthenticatedBroadcastsRouteRouteImport } from './routes/_authenticated/broadcasts/route'
import { Route as AuthenticatedAesRouteRouteImport } from './routes/_authenticated/aes/route'
import { Route as AuthenticatedWorkflowsIndexRouteImport } from './routes/_authenticated/workflows/index'
import { Route as AuthenticatedWorkflowInstancesIndexRouteImport } from './routes/_authenticated/workflow-instances/index'
import { Route as AuthenticatedWorkflowEventsIndexRouteImport } from './routes/_authenticated/workflow-events/index'
import { Route as AuthenticatedWorkflowConfigurationIndexRouteImport } from './routes/_authenticated/workflow-configuration/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedUomsIndexRouteImport } from './routes/_authenticated/uoms/index'
import { Route as AuthenticatedSuppliersIndexRouteImport } from './routes/_authenticated/suppliers/index'
import { Route as AuthenticatedStockLocationsIndexRouteImport } from './routes/_authenticated/stock-locations/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSalesIndexRouteImport } from './routes/_authenticated/sales/index'
import { Route as AuthenticatedRolesIndexRouteImport } from './routes/_authenticated/roles/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedReceivablesIndexRouteImport } from './routes/_authenticated/receivables/index'
import { Route as AuthenticatedQuestionsIndexRouteImport } from './routes/_authenticated/questions/index'
import { Route as AuthenticatedQuestionnairesIndexRouteImport } from './routes/_authenticated/questionnaires/index'
import { Route as AuthenticatedPurchasesIndexRouteImport } from './routes/_authenticated/purchases/index'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products/index'
import { Route as AuthenticatedPriceListsIndexRouteImport } from './routes/_authenticated/price-lists/index'
import { Route as AuthenticatedPriceListItemsIndexRouteImport } from './routes/_authenticated/price-list-items/index'
import { Route as AuthenticatedPharmaceuticsIndexRouteImport } from './routes/_authenticated/pharmaceutics/index'
import { Route as AuthenticatedPaymentMethodsIndexRouteImport } from './routes/_authenticated/payment-methods/index'
import { Route as AuthenticatedParticipantsIndexRouteImport } from './routes/_authenticated/participants/index'
import { Route as AuthenticatedOrganizationsIndexRouteImport } from './routes/_authenticated/organizations/index'
import { Route as AuthenticatedManufacturersIndexRouteImport } from './routes/_authenticated/manufacturers/index'
import { Route as AuthenticatedLisIndexRouteImport } from './routes/_authenticated/lis/index'
import { Route as AuthenticatedJournalsIndexRouteImport } from './routes/_authenticated/journals/index'
import { Route as AuthenticatedJournalEntryLinesIndexRouteImport } from './routes/_authenticated/journal-entry-lines/index'
import { Route as AuthenticatedJournalEntriesIndexRouteImport } from './routes/_authenticated/journal-entries/index'
import { Route as AuthenticatedInventoryIndexRouteImport } from './routes/_authenticated/inventory/index'
import { Route as AuthenticatedExchangesIndexRouteImport } from './routes/_authenticated/exchanges/index'
import { Route as AuthenticatedDrugComponentsIndexRouteImport } from './routes/_authenticated/drug-components/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedConversationsIndexRouteImport } from './routes/_authenticated/conversations/index'
import { Route as AuthenticatedCodingConceptsIndexRouteImport } from './routes/_authenticated/coding-concepts/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedChannelsIndexRouteImport } from './routes/_authenticated/channels/index'
import { Route as AuthenticatedCategoriesIndexRouteImport } from './routes/_authenticated/categories/index'
import { Route as AuthenticatedBranchesIndexRouteImport } from './routes/_authenticated/branches/index'
import { Route as AuthenticatedAuditLogsIndexRouteImport } from './routes/_authenticated/audit-logs/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as AuthenticatedUomsUomIdRouteImport } from './routes/_authenticated/uoms/$uomId'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedProductsProductIdRouteImport } from './routes/_authenticated/products/$productId'
import { Route as AuthenticatedLisResourceKeyRouteImport } from './routes/_authenticated/lis/$resourceKey'
import { Route as AuthenticatedCommunicationTraceExplorerRouteImport } from './routes/_authenticated/communication/trace-explorer'
import { Route as AuthenticatedCommunicationMessageTesterRouteImport } from './routes/_authenticated/communication/message-tester'
import { Route as AuthenticatedCommunicationFlowGraphRouteImport } from './routes/_authenticated/communication/flow-graph'
import { Route as AuthenticatedCommunicationAuditCenterRouteImport } from './routes/_authenticated/communication/audit-center'
import { Route as AuthenticatedCodingConceptsUploadRouteImport } from './routes/_authenticated/coding-concepts/upload'
import { Route as AuthenticatedCodingConceptsSearchRouteImport } from './routes/_authenticated/coding-concepts/search'
import { Route as AuthenticatedCodingConceptsMatchRouteImport } from './routes/_authenticated/coding-concepts/match'
import { Route as AuthenticatedUomsUomIdEditRouteImport } from './routes/_authenticated/uoms/$uomId/edit'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireIndexRoute = QuestionnaireIndexRouteImport.update({
  id: '/questionnaire/',
  path: '/questionnaire/',
  getParentRoute: () => rootRouteImport,
} as any)
const DamorexIndexRoute = DamorexIndexRouteImport.update({
  id: '/damorex/',
  path: '/damorex/',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoutingRouteRoute =
  AuthenticatedRoutingRouteRouteImport.update({
    id: '/routing',
    path: '/routing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsRouteRoute =
  AuthenticatedNotificationsRouteRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationTemplatesRouteRoute =
  AuthenticatedNotificationTemplatesRouteRouteImport.update({
    id: '/notification-templates',
    path: '/notification-templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesRouteRoute =
  AuthenticatedMessagesRouteRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessageTemplatesRouteRoute =
  AuthenticatedMessageTemplatesRouteRouteImport.update({
    id: '/message-templates',
    path: '/message-templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessageLogsRouteRoute =
  AuthenticatedMessageLogsRouteRouteImport.update({
    id: '/message-logs',
    path: '/message-logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMappingRouteRoute =
  AuthenticatedMappingRouteRouteImport.update({
    id: '/mapping',
    path: '/mapping',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommunicationChannelsRouteRoute =
  AuthenticatedCommunicationChannelsRouteRouteImport.update({
    id: '/communication-channels',
    path: '/communication-channels',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBroadcastsRouteRoute =
  AuthenticatedBroadcastsRouteRouteImport.update({
    id: '/broadcasts',
    path: '/broadcasts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAesRouteRoute = AuthenticatedAesRouteRouteImport.update({
  id: '/aes',
  path: '/aes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkflowsIndexRoute =
  AuthenticatedWorkflowsIndexRouteImport.update({
    id: '/workflows/',
    path: '/workflows/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkflowInstancesIndexRoute =
  AuthenticatedWorkflowInstancesIndexRouteImport.update({
    id: '/workflow-instances/',
    path: '/workflow-instances/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkflowEventsIndexRoute =
  AuthenticatedWorkflowEventsIndexRouteImport.update({
    id: '/workflow-events/',
    path: '/workflow-events/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkflowConfigurationIndexRoute =
  AuthenticatedWorkflowConfigurationIndexRouteImport.update({
    id: '/workflow-configuration/',
    path: '/workflow-configuration/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUomsIndexRoute = AuthenticatedUomsIndexRouteImport.update({
  id: '/uoms/',
  path: '/uoms/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuppliersIndexRoute =
  AuthenticatedSuppliersIndexRouteImport.update({
    id: '/suppliers/',
    path: '/suppliers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStockLocationsIndexRoute =
  AuthenticatedStockLocationsIndexRouteImport.update({
    id: '/stock-locations/',
    path: '/stock-locations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSalesIndexRoute = AuthenticatedSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRolesIndexRoute = AuthenticatedRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReceivablesIndexRoute =
  AuthenticatedReceivablesIndexRouteImport.update({
    id: '/receivables/',
    path: '/receivables/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuestionsIndexRoute =
  AuthenticatedQuestionsIndexRouteImport.update({
    id: '/questions/',
    path: '/questions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuestionnairesIndexRoute =
  AuthenticatedQuestionnairesIndexRouteImport.update({
    id: '/questionnaires/',
    path: '/questionnaires/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasesIndexRoute =
  AuthenticatedPurchasesIndexRouteImport.update({
    id: '/purchases/',
    path: '/purchases/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPriceListsIndexRoute =
  AuthenticatedPriceListsIndexRouteImport.update({
    id: '/price-lists/',
    path: '/price-lists/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPriceListItemsIndexRoute =
  AuthenticatedPriceListItemsIndexRouteImport.update({
    id: '/price-list-items/',
    path: '/price-list-items/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPharmaceuticsIndexRoute =
  AuthenticatedPharmaceuticsIndexRouteImport.update({
    id: '/pharmaceutics/',
    path: '/pharmaceutics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentMethodsIndexRoute =
  AuthenticatedPaymentMethodsIndexRouteImport.update({
    id: '/payment-methods/',
    path: '/payment-methods/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParticipantsIndexRoute =
  AuthenticatedParticipantsIndexRouteImport.update({
    id: '/participants/',
    path: '/participants/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizationsIndexRoute =
  AuthenticatedOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManufacturersIndexRoute =
  AuthenticatedManufacturersIndexRouteImport.update({
    id: '/manufacturers/',
    path: '/manufacturers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLisIndexRoute = AuthenticatedLisIndexRouteImport.update({
  id: '/lis/',
  path: '/lis/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJournalsIndexRoute =
  AuthenticatedJournalsIndexRouteImport.update({
    id: '/journals/',
    path: '/journals/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJournalEntryLinesIndexRoute =
  AuthenticatedJournalEntryLinesIndexRouteImport.update({
    id: '/journal-entry-lines/',
    path: '/journal-entry-lines/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJournalEntriesIndexRoute =
  AuthenticatedJournalEntriesIndexRouteImport.update({
    id: '/journal-entries/',
    path: '/journal-entries/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryIndexRoute =
  AuthenticatedInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExchangesIndexRoute =
  AuthenticatedExchangesIndexRouteImport.update({
    id: '/exchanges/',
    path: '/exchanges/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDrugComponentsIndexRoute =
  AuthenticatedDrugComponentsIndexRouteImport.update({
    id: '/drug-components/',
    path: '/drug-components/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConversationsIndexRoute =
  AuthenticatedConversationsIndexRouteImport.update({
    id: '/conversations/',
    path: '/conversations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCodingConceptsIndexRoute =
  AuthenticatedCodingConceptsIndexRouteImport.update({
    id: '/coding-concepts/',
    path: '/coding-concepts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChannelsIndexRoute =
  AuthenticatedChannelsIndexRouteImport.update({
    id: '/channels/',
    path: '/channels/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCategoriesIndexRoute =
  AuthenticatedCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBranchesIndexRoute =
  AuthenticatedBranchesIndexRouteImport.update({
    id: '/branches/',
    path: '/branches/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditLogsIndexRoute =
  AuthenticatedAuditLogsIndexRouteImport.update({
    id: '/audit-logs/',
    path: '/audit-logs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const AuthenticatedUomsUomIdRoute = AuthenticatedUomsUomIdRouteImport.update({
  id: '/uoms/$uomId',
  path: '/uoms/$uomId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedProductsProductIdRoute =
  AuthenticatedProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLisResourceKeyRoute =
  AuthenticatedLisResourceKeyRouteImport.update({
    id: '/lis/$resourceKey',
    path: '/lis/$resourceKey',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommunicationTraceExplorerRoute =
  AuthenticatedCommunicationTraceExplorerRouteImport.update({
    id: '/communication/trace-explorer',
    path: '/communication/trace-explorer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommunicationMessageTesterRoute =
  AuthenticatedCommunicationMessageTesterRouteImport.update({
    id: '/communication/message-tester',
    path: '/communication/message-tester',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommunicationFlowGraphRoute =
  AuthenticatedCommunicationFlowGraphRouteImport.update({
    id: '/communication/flow-graph',
    path: '/communication/flow-graph',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommunicationAuditCenterRoute =
  AuthenticatedCommunicationAuditCenterRouteImport.update({
    id: '/communication/audit-center',
    path: '/communication/audit-center',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCodingConceptsUploadRoute =
  AuthenticatedCodingConceptsUploadRouteImport.update({
    id: '/coding-concepts/upload',
    path: '/coding-concepts/upload',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCodingConceptsSearchRoute =
  AuthenticatedCodingConceptsSearchRouteImport.update({
    id: '/coding-concepts/search',
    path: '/coding-concepts/search',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCodingConceptsMatchRoute =
  AuthenticatedCodingConceptsMatchRouteImport.update({
    id: '/coding-concepts/match',
    path: '/coding-concepts/match',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUomsUomIdEditRoute =
  AuthenticatedUomsUomIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedUomsUomIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/aes': typeof AuthenticatedAesRouteRoute
  '/broadcasts': typeof AuthenticatedBroadcastsRouteRoute
  '/communication-channels': typeof AuthenticatedCommunicationChannelsRouteRoute
  '/mapping': typeof AuthenticatedMappingRouteRoute
  '/message-logs': typeof AuthenticatedMessageLogsRouteRoute
  '/message-templates': typeof AuthenticatedMessageTemplatesRouteRoute
  '/messages': typeof AuthenticatedMessagesRouteRoute
  '/notification-templates': typeof AuthenticatedNotificationTemplatesRouteRoute
  '/notifications': typeof AuthenticatedNotificationsRouteRoute
  '/routing': typeof AuthenticatedRoutingRouteRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/damorex/': typeof DamorexIndexRoute
  '/questionnaire/': typeof QuestionnaireIndexRoute
  '/coding-concepts/match': typeof AuthenticatedCodingConceptsMatchRoute
  '/coding-concepts/search': typeof AuthenticatedCodingConceptsSearchRoute
  '/coding-concepts/upload': typeof AuthenticatedCodingConceptsUploadRoute
  '/communication/audit-center': typeof AuthenticatedCommunicationAuditCenterRoute
  '/communication/flow-graph': typeof AuthenticatedCommunicationFlowGraphRoute
  '/communication/message-tester': typeof AuthenticatedCommunicationMessageTesterRoute
  '/communication/trace-explorer': typeof AuthenticatedCommunicationTraceExplorerRoute
  '/lis/$resourceKey': typeof AuthenticatedLisResourceKeyRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/uoms/$uomId': typeof AuthenticatedUomsUomIdRouteWithChildren
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/audit-logs/': typeof AuthenticatedAuditLogsIndexRoute
  '/branches/': typeof AuthenticatedBranchesIndexRoute
  '/categories/': typeof AuthenticatedCategoriesIndexRoute
  '/channels/': typeof AuthenticatedChannelsIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/coding-concepts/': typeof AuthenticatedCodingConceptsIndexRoute
  '/conversations/': typeof AuthenticatedConversationsIndexRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/drug-components/': typeof AuthenticatedDrugComponentsIndexRoute
  '/exchanges/': typeof AuthenticatedExchangesIndexRoute
  '/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/journal-entries/': typeof AuthenticatedJournalEntriesIndexRoute
  '/journal-entry-lines/': typeof AuthenticatedJournalEntryLinesIndexRoute
  '/journals/': typeof AuthenticatedJournalsIndexRoute
  '/lis/': typeof AuthenticatedLisIndexRoute
  '/manufacturers/': typeof AuthenticatedManufacturersIndexRoute
  '/organizations/': typeof AuthenticatedOrganizationsIndexRoute
  '/participants/': typeof AuthenticatedParticipantsIndexRoute
  '/payment-methods/': typeof AuthenticatedPaymentMethodsIndexRoute
  '/pharmaceutics/': typeof AuthenticatedPharmaceuticsIndexRoute
  '/price-list-items/': typeof AuthenticatedPriceListItemsIndexRoute
  '/price-lists/': typeof AuthenticatedPriceListsIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/purchases/': typeof AuthenticatedPurchasesIndexRoute
  '/questionnaires/': typeof AuthenticatedQuestionnairesIndexRoute
  '/questions/': typeof AuthenticatedQuestionsIndexRoute
  '/receivables/': typeof AuthenticatedReceivablesIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/roles/': typeof AuthenticatedRolesIndexRoute
  '/sales/': typeof AuthenticatedSalesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/stock-locations/': typeof AuthenticatedStockLocationsIndexRoute
  '/suppliers/': typeof AuthenticatedSuppliersIndexRoute
  '/uoms/': typeof AuthenticatedUomsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/workflow-configuration/': typeof AuthenticatedWorkflowConfigurationIndexRoute
  '/workflow-events/': typeof AuthenticatedWorkflowEventsIndexRoute
  '/workflow-instances/': typeof AuthenticatedWorkflowInstancesIndexRoute
  '/workflows/': typeof AuthenticatedWorkflowsIndexRoute
  '/uoms/$uomId/edit': typeof AuthenticatedUomsUomIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/aes': typeof AuthenticatedAesRouteRoute
  '/broadcasts': typeof AuthenticatedBroadcastsRouteRoute
  '/communication-channels': typeof AuthenticatedCommunicationChannelsRouteRoute
  '/mapping': typeof AuthenticatedMappingRouteRoute
  '/message-logs': typeof AuthenticatedMessageLogsRouteRoute
  '/message-templates': typeof AuthenticatedMessageTemplatesRouteRoute
  '/messages': typeof AuthenticatedMessagesRouteRoute
  '/notification-templates': typeof AuthenticatedNotificationTemplatesRouteRoute
  '/notifications': typeof AuthenticatedNotificationsRouteRoute
  '/routing': typeof AuthenticatedRoutingRouteRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/damorex': typeof DamorexIndexRoute
  '/questionnaire': typeof QuestionnaireIndexRoute
  '/coding-concepts/match': typeof AuthenticatedCodingConceptsMatchRoute
  '/coding-concepts/search': typeof AuthenticatedCodingConceptsSearchRoute
  '/coding-concepts/upload': typeof AuthenticatedCodingConceptsUploadRoute
  '/communication/audit-center': typeof AuthenticatedCommunicationAuditCenterRoute
  '/communication/flow-graph': typeof AuthenticatedCommunicationFlowGraphRoute
  '/communication/message-tester': typeof AuthenticatedCommunicationMessageTesterRoute
  '/communication/trace-explorer': typeof AuthenticatedCommunicationTraceExplorerRoute
  '/lis/$resourceKey': typeof AuthenticatedLisResourceKeyRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/uoms/$uomId': typeof AuthenticatedUomsUomIdRouteWithChildren
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/audit-logs': typeof AuthenticatedAuditLogsIndexRoute
  '/branches': typeof AuthenticatedBranchesIndexRoute
  '/categories': typeof AuthenticatedCategoriesIndexRoute
  '/channels': typeof AuthenticatedChannelsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/coding-concepts': typeof AuthenticatedCodingConceptsIndexRoute
  '/conversations': typeof AuthenticatedConversationsIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/drug-components': typeof AuthenticatedDrugComponentsIndexRoute
  '/exchanges': typeof AuthenticatedExchangesIndexRoute
  '/inventory': typeof AuthenticatedInventoryIndexRoute
  '/journal-entries': typeof AuthenticatedJournalEntriesIndexRoute
  '/journal-entry-lines': typeof AuthenticatedJournalEntryLinesIndexRoute
  '/journals': typeof AuthenticatedJournalsIndexRoute
  '/lis': typeof AuthenticatedLisIndexRoute
  '/manufacturers': typeof AuthenticatedManufacturersIndexRoute
  '/organizations': typeof AuthenticatedOrganizationsIndexRoute
  '/participants': typeof AuthenticatedParticipantsIndexRoute
  '/payment-methods': typeof AuthenticatedPaymentMethodsIndexRoute
  '/pharmaceutics': typeof AuthenticatedPharmaceuticsIndexRoute
  '/price-list-items': typeof AuthenticatedPriceListItemsIndexRoute
  '/price-lists': typeof AuthenticatedPriceListsIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/purchases': typeof AuthenticatedPurchasesIndexRoute
  '/questionnaires': typeof AuthenticatedQuestionnairesIndexRoute
  '/questions': typeof AuthenticatedQuestionsIndexRoute
  '/receivables': typeof AuthenticatedReceivablesIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/sales': typeof AuthenticatedSalesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/stock-locations': typeof AuthenticatedStockLocationsIndexRoute
  '/suppliers': typeof AuthenticatedSuppliersIndexRoute
  '/uoms': typeof AuthenticatedUomsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/workflow-configuration': typeof AuthenticatedWorkflowConfigurationIndexRoute
  '/workflow-events': typeof AuthenticatedWorkflowEventsIndexRoute
  '/workflow-instances': typeof AuthenticatedWorkflowInstancesIndexRoute
  '/workflows': typeof AuthenticatedWorkflowsIndexRoute
  '/uoms/$uomId/edit': typeof AuthenticatedUomsUomIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/aes': typeof AuthenticatedAesRouteRoute
  '/_authenticated/broadcasts': typeof AuthenticatedBroadcastsRouteRoute
  '/_authenticated/communication-channels': typeof AuthenticatedCommunicationChannelsRouteRoute
  '/_authenticated/mapping': typeof AuthenticatedMappingRouteRoute
  '/_authenticated/message-logs': typeof AuthenticatedMessageLogsRouteRoute
  '/_authenticated/message-templates': typeof AuthenticatedMessageTemplatesRouteRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRouteRoute
  '/_authenticated/notification-templates': typeof AuthenticatedNotificationTemplatesRouteRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRouteRoute
  '/_authenticated/routing': typeof AuthenticatedRoutingRouteRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRoute
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/damorex/': typeof DamorexIndexRoute
  '/questionnaire/': typeof QuestionnaireIndexRoute
  '/_authenticated/coding-concepts/match': typeof AuthenticatedCodingConceptsMatchRoute
  '/_authenticated/coding-concepts/search': typeof AuthenticatedCodingConceptsSearchRoute
  '/_authenticated/coding-concepts/upload': typeof AuthenticatedCodingConceptsUploadRoute
  '/_authenticated/communication/audit-center': typeof AuthenticatedCommunicationAuditCenterRoute
  '/_authenticated/communication/flow-graph': typeof AuthenticatedCommunicationFlowGraphRoute
  '/_authenticated/communication/message-tester': typeof AuthenticatedCommunicationMessageTesterRoute
  '/_authenticated/communication/trace-explorer': typeof AuthenticatedCommunicationTraceExplorerRoute
  '/_authenticated/lis/$resourceKey': typeof AuthenticatedLisResourceKeyRoute
  '/_authenticated/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/uoms/$uomId': typeof AuthenticatedUomsUomIdRouteWithChildren
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/audit-logs/': typeof AuthenticatedAuditLogsIndexRoute
  '/_authenticated/branches/': typeof AuthenticatedBranchesIndexRoute
  '/_authenticated/categories/': typeof AuthenticatedCategoriesIndexRoute
  '/_authenticated/channels/': typeof AuthenticatedChannelsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/coding-concepts/': typeof AuthenticatedCodingConceptsIndexRoute
  '/_authenticated/conversations/': typeof AuthenticatedConversationsIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/drug-components/': typeof AuthenticatedDrugComponentsIndexRoute
  '/_authenticated/exchanges/': typeof AuthenticatedExchangesIndexRoute
  '/_authenticated/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/_authenticated/journal-entries/': typeof AuthenticatedJournalEntriesIndexRoute
  '/_authenticated/journal-entry-lines/': typeof AuthenticatedJournalEntryLinesIndexRoute
  '/_authenticated/journals/': typeof AuthenticatedJournalsIndexRoute
  '/_authenticated/lis/': typeof AuthenticatedLisIndexRoute
  '/_authenticated/manufacturers/': typeof AuthenticatedManufacturersIndexRoute
  '/_authenticated/organizations/': typeof AuthenticatedOrganizationsIndexRoute
  '/_authenticated/participants/': typeof AuthenticatedParticipantsIndexRoute
  '/_authenticated/payment-methods/': typeof AuthenticatedPaymentMethodsIndexRoute
  '/_authenticated/pharmaceutics/': typeof AuthenticatedPharmaceuticsIndexRoute
  '/_authenticated/price-list-items/': typeof AuthenticatedPriceListItemsIndexRoute
  '/_authenticated/price-lists/': typeof AuthenticatedPriceListsIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/purchases/': typeof AuthenticatedPurchasesIndexRoute
  '/_authenticated/questionnaires/': typeof AuthenticatedQuestionnairesIndexRoute
  '/_authenticated/questions/': typeof AuthenticatedQuestionsIndexRoute
  '/_authenticated/receivables/': typeof AuthenticatedReceivablesIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/roles/': typeof AuthenticatedRolesIndexRoute
  '/_authenticated/sales/': typeof AuthenticatedSalesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/stock-locations/': typeof AuthenticatedStockLocationsIndexRoute
  '/_authenticated/suppliers/': typeof AuthenticatedSuppliersIndexRoute
  '/_authenticated/uoms/': typeof AuthenticatedUomsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/workflow-configuration/': typeof AuthenticatedWorkflowConfigurationIndexRoute
  '/_authenticated/workflow-events/': typeof AuthenticatedWorkflowEventsIndexRoute
  '/_authenticated/workflow-instances/': typeof AuthenticatedWorkflowInstancesIndexRoute
  '/_authenticated/workflows/': typeof AuthenticatedWorkflowsIndexRoute
  '/_authenticated/uoms/$uomId/edit': typeof AuthenticatedUomsUomIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clerk'
    | '/aes'
    | '/broadcasts'
    | '/communication-channels'
    | '/mapping'
    | '/message-logs'
    | '/message-templates'
    | '/messages'
    | '/notification-templates'
    | '/notifications'
    | '/routing'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/damorex/'
    | '/questionnaire/'
    | '/coding-concepts/match'
    | '/coding-concepts/search'
    | '/coding-concepts/upload'
    | '/communication/audit-center'
    | '/communication/flow-graph'
    | '/communication/message-tester'
    | '/communication/trace-explorer'
    | '/lis/$resourceKey'
    | '/products/$productId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/uoms/$uomId'
    | '/clerk/user-management'
    | '/audit-logs/'
    | '/branches/'
    | '/categories/'
    | '/channels/'
    | '/chats/'
    | '/coding-concepts/'
    | '/conversations/'
    | '/customers/'
    | '/dashboard/'
    | '/drug-components/'
    | '/exchanges/'
    | '/inventory/'
    | '/journal-entries/'
    | '/journal-entry-lines/'
    | '/journals/'
    | '/lis/'
    | '/manufacturers/'
    | '/organizations/'
    | '/participants/'
    | '/payment-methods/'
    | '/pharmaceutics/'
    | '/price-list-items/'
    | '/price-lists/'
    | '/products/'
    | '/purchases/'
    | '/questionnaires/'
    | '/questions/'
    | '/receivables/'
    | '/reports/'
    | '/roles/'
    | '/sales/'
    | '/settings/'
    | '/stock-locations/'
    | '/suppliers/'
    | '/uoms/'
    | '/users/'
    | '/workflow-configuration/'
    | '/workflow-events/'
    | '/workflow-instances/'
    | '/workflows/'
    | '/uoms/$uomId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clerk'
    | '/aes'
    | '/broadcasts'
    | '/communication-channels'
    | '/mapping'
    | '/message-logs'
    | '/message-templates'
    | '/messages'
    | '/notification-templates'
    | '/notifications'
    | '/routing'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/damorex'
    | '/questionnaire'
    | '/coding-concepts/match'
    | '/coding-concepts/search'
    | '/coding-concepts/upload'
    | '/communication/audit-center'
    | '/communication/flow-graph'
    | '/communication/message-tester'
    | '/communication/trace-explorer'
    | '/lis/$resourceKey'
    | '/products/$productId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/uoms/$uomId'
    | '/clerk/user-management'
    | '/audit-logs'
    | '/branches'
    | '/categories'
    | '/channels'
    | '/chats'
    | '/coding-concepts'
    | '/conversations'
    | '/customers'
    | '/dashboard'
    | '/drug-components'
    | '/exchanges'
    | '/inventory'
    | '/journal-entries'
    | '/journal-entry-lines'
    | '/journals'
    | '/lis'
    | '/manufacturers'
    | '/organizations'
    | '/participants'
    | '/payment-methods'
    | '/pharmaceutics'
    | '/price-list-items'
    | '/price-lists'
    | '/products'
    | '/purchases'
    | '/questionnaires'
    | '/questions'
    | '/receivables'
    | '/reports'
    | '/roles'
    | '/sales'
    | '/settings'
    | '/stock-locations'
    | '/suppliers'
    | '/uoms'
    | '/users'
    | '/workflow-configuration'
    | '/workflow-events'
    | '/workflow-instances'
    | '/workflows'
    | '/uoms/$uomId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/aes'
    | '/_authenticated/broadcasts'
    | '/_authenticated/communication-channels'
    | '/_authenticated/mapping'
    | '/_authenticated/message-logs'
    | '/_authenticated/message-templates'
    | '/_authenticated/messages'
    | '/_authenticated/notification-templates'
    | '/_authenticated/notifications'
    | '/_authenticated/routing'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/damorex/'
    | '/questionnaire/'
    | '/_authenticated/coding-concepts/match'
    | '/_authenticated/coding-concepts/search'
    | '/_authenticated/coding-concepts/upload'
    | '/_authenticated/communication/audit-center'
    | '/_authenticated/communication/flow-graph'
    | '/_authenticated/communication/message-tester'
    | '/_authenticated/communication/trace-explorer'
    | '/_authenticated/lis/$resourceKey'
    | '/_authenticated/products/$productId'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/uoms/$uomId'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/audit-logs/'
    | '/_authenticated/branches/'
    | '/_authenticated/categories/'
    | '/_authenticated/channels/'
    | '/_authenticated/chats/'
    | '/_authenticated/coding-concepts/'
    | '/_authenticated/conversations/'
    | '/_authenticated/customers/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/drug-components/'
    | '/_authenticated/exchanges/'
    | '/_authenticated/inventory/'
    | '/_authenticated/journal-entries/'
    | '/_authenticated/journal-entry-lines/'
    | '/_authenticated/journals/'
    | '/_authenticated/lis/'
    | '/_authenticated/manufacturers/'
    | '/_authenticated/organizations/'
    | '/_authenticated/participants/'
    | '/_authenticated/payment-methods/'
    | '/_authenticated/pharmaceutics/'
    | '/_authenticated/price-list-items/'
    | '/_authenticated/price-lists/'
    | '/_authenticated/products/'
    | '/_authenticated/purchases/'
    | '/_authenticated/questionnaires/'
    | '/_authenticated/questions/'
    | '/_authenticated/receivables/'
    | '/_authenticated/reports/'
    | '/_authenticated/roles/'
    | '/_authenticated/sales/'
    | '/_authenticated/settings/'
    | '/_authenticated/stock-locations/'
    | '/_authenticated/suppliers/'
    | '/_authenticated/uoms/'
    | '/_authenticated/users/'
    | '/_authenticated/workflow-configuration/'
    | '/_authenticated/workflow-events/'
    | '/_authenticated/workflow-instances/'
    | '/_authenticated/workflows/'
    | '/_authenticated/uoms/$uomId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  DamorexIndexRoute: typeof DamorexIndexRoute
  QuestionnaireIndexRoute: typeof QuestionnaireIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire/': {
      id: '/questionnaire/'
      path: '/questionnaire'
      fullPath: '/questionnaire/'
      preLoaderRoute: typeof QuestionnaireIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/damorex/': {
      id: '/damorex/'
      path: '/damorex'
      fullPath: '/damorex/'
      preLoaderRoute: typeof DamorexIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/routing': {
      id: '/_authenticated/routing'
      path: '/routing'
      fullPath: '/routing'
      preLoaderRoute: typeof AuthenticatedRoutingRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notification-templates': {
      id: '/_authenticated/notification-templates'
      path: '/notification-templates'
      fullPath: '/notification-templates'
      preLoaderRoute: typeof AuthenticatedNotificationTemplatesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/message-templates': {
      id: '/_authenticated/message-templates'
      path: '/message-templates'
      fullPath: '/message-templates'
      preLoaderRoute: typeof AuthenticatedMessageTemplatesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/message-logs': {
      id: '/_authenticated/message-logs'
      path: '/message-logs'
      fullPath: '/message-logs'
      preLoaderRoute: typeof AuthenticatedMessageLogsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mapping': {
      id: '/_authenticated/mapping'
      path: '/mapping'
      fullPath: '/mapping'
      preLoaderRoute: typeof AuthenticatedMappingRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/communication-channels': {
      id: '/_authenticated/communication-channels'
      path: '/communication-channels'
      fullPath: '/communication-channels'
      preLoaderRoute: typeof AuthenticatedCommunicationChannelsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/broadcasts': {
      id: '/_authenticated/broadcasts'
      path: '/broadcasts'
      fullPath: '/broadcasts'
      preLoaderRoute: typeof AuthenticatedBroadcastsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aes': {
      id: '/_authenticated/aes'
      path: '/aes'
      fullPath: '/aes'
      preLoaderRoute: typeof AuthenticatedAesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workflows/': {
      id: '/_authenticated/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof AuthenticatedWorkflowsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workflow-instances/': {
      id: '/_authenticated/workflow-instances/'
      path: '/workflow-instances'
      fullPath: '/workflow-instances/'
      preLoaderRoute: typeof AuthenticatedWorkflowInstancesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workflow-events/': {
      id: '/_authenticated/workflow-events/'
      path: '/workflow-events'
      fullPath: '/workflow-events/'
      preLoaderRoute: typeof AuthenticatedWorkflowEventsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workflow-configuration/': {
      id: '/_authenticated/workflow-configuration/'
      path: '/workflow-configuration'
      fullPath: '/workflow-configuration/'
      preLoaderRoute: typeof AuthenticatedWorkflowConfigurationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/uoms/': {
      id: '/_authenticated/uoms/'
      path: '/uoms'
      fullPath: '/uoms/'
      preLoaderRoute: typeof AuthenticatedUomsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers/': {
      id: '/_authenticated/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof AuthenticatedSuppliersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock-locations/': {
      id: '/_authenticated/stock-locations/'
      path: '/stock-locations'
      fullPath: '/stock-locations/'
      preLoaderRoute: typeof AuthenticatedStockLocationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/sales/': {
      id: '/_authenticated/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof AuthenticatedSalesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles/': {
      id: '/_authenticated/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AuthenticatedRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receivables/': {
      id: '/_authenticated/receivables/'
      path: '/receivables'
      fullPath: '/receivables/'
      preLoaderRoute: typeof AuthenticatedReceivablesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/questions/': {
      id: '/_authenticated/questions/'
      path: '/questions'
      fullPath: '/questions/'
      preLoaderRoute: typeof AuthenticatedQuestionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/questionnaires/': {
      id: '/_authenticated/questionnaires/'
      path: '/questionnaires'
      fullPath: '/questionnaires/'
      preLoaderRoute: typeof AuthenticatedQuestionnairesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchases/': {
      id: '/_authenticated/purchases/'
      path: '/purchases'
      fullPath: '/purchases/'
      preLoaderRoute: typeof AuthenticatedPurchasesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/price-lists/': {
      id: '/_authenticated/price-lists/'
      path: '/price-lists'
      fullPath: '/price-lists/'
      preLoaderRoute: typeof AuthenticatedPriceListsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/price-list-items/': {
      id: '/_authenticated/price-list-items/'
      path: '/price-list-items'
      fullPath: '/price-list-items/'
      preLoaderRoute: typeof AuthenticatedPriceListItemsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pharmaceutics/': {
      id: '/_authenticated/pharmaceutics/'
      path: '/pharmaceutics'
      fullPath: '/pharmaceutics/'
      preLoaderRoute: typeof AuthenticatedPharmaceuticsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment-methods/': {
      id: '/_authenticated/payment-methods/'
      path: '/payment-methods'
      fullPath: '/payment-methods/'
      preLoaderRoute: typeof AuthenticatedPaymentMethodsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/participants/': {
      id: '/_authenticated/participants/'
      path: '/participants'
      fullPath: '/participants/'
      preLoaderRoute: typeof AuthenticatedParticipantsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizations/': {
      id: '/_authenticated/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AuthenticatedOrganizationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manufacturers/': {
      id: '/_authenticated/manufacturers/'
      path: '/manufacturers'
      fullPath: '/manufacturers/'
      preLoaderRoute: typeof AuthenticatedManufacturersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lis/': {
      id: '/_authenticated/lis/'
      path: '/lis'
      fullPath: '/lis/'
      preLoaderRoute: typeof AuthenticatedLisIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journals/': {
      id: '/_authenticated/journals/'
      path: '/journals'
      fullPath: '/journals/'
      preLoaderRoute: typeof AuthenticatedJournalsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal-entry-lines/': {
      id: '/_authenticated/journal-entry-lines/'
      path: '/journal-entry-lines'
      fullPath: '/journal-entry-lines/'
      preLoaderRoute: typeof AuthenticatedJournalEntryLinesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal-entries/': {
      id: '/_authenticated/journal-entries/'
      path: '/journal-entries'
      fullPath: '/journal-entries/'
      preLoaderRoute: typeof AuthenticatedJournalEntriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/': {
      id: '/_authenticated/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthenticatedInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exchanges/': {
      id: '/_authenticated/exchanges/'
      path: '/exchanges'
      fullPath: '/exchanges/'
      preLoaderRoute: typeof AuthenticatedExchangesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drug-components/': {
      id: '/_authenticated/drug-components/'
      path: '/drug-components'
      fullPath: '/drug-components/'
      preLoaderRoute: typeof AuthenticatedDrugComponentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversations/': {
      id: '/_authenticated/conversations/'
      path: '/conversations'
      fullPath: '/conversations/'
      preLoaderRoute: typeof AuthenticatedConversationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coding-concepts/': {
      id: '/_authenticated/coding-concepts/'
      path: '/coding-concepts'
      fullPath: '/coding-concepts/'
      preLoaderRoute: typeof AuthenticatedCodingConceptsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/channels/': {
      id: '/_authenticated/channels/'
      path: '/channels'
      fullPath: '/channels/'
      preLoaderRoute: typeof AuthenticatedChannelsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories/': {
      id: '/_authenticated/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof AuthenticatedCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/branches/': {
      id: '/_authenticated/branches/'
      path: '/branches'
      fullPath: '/branches/'
      preLoaderRoute: typeof AuthenticatedBranchesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-logs/': {
      id: '/_authenticated/audit-logs/'
      path: '/audit-logs'
      fullPath: '/audit-logs/'
      preLoaderRoute: typeof AuthenticatedAuditLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/_authenticated/uoms/$uomId': {
      id: '/_authenticated/uoms/$uomId'
      path: '/uoms/$uomId'
      fullPath: '/uoms/$uomId'
      preLoaderRoute: typeof AuthenticatedUomsUomIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/products/$productId': {
      id: '/_authenticated/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AuthenticatedProductsProductIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lis/$resourceKey': {
      id: '/_authenticated/lis/$resourceKey'
      path: '/lis/$resourceKey'
      fullPath: '/lis/$resourceKey'
      preLoaderRoute: typeof AuthenticatedLisResourceKeyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/communication/trace-explorer': {
      id: '/_authenticated/communication/trace-explorer'
      path: '/communication/trace-explorer'
      fullPath: '/communication/trace-explorer'
      preLoaderRoute: typeof AuthenticatedCommunicationTraceExplorerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/communication/message-tester': {
      id: '/_authenticated/communication/message-tester'
      path: '/communication/message-tester'
      fullPath: '/communication/message-tester'
      preLoaderRoute: typeof AuthenticatedCommunicationMessageTesterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/communication/flow-graph': {
      id: '/_authenticated/communication/flow-graph'
      path: '/communication/flow-graph'
      fullPath: '/communication/flow-graph'
      preLoaderRoute: typeof AuthenticatedCommunicationFlowGraphRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/communication/audit-center': {
      id: '/_authenticated/communication/audit-center'
      path: '/communication/audit-center'
      fullPath: '/communication/audit-center'
      preLoaderRoute: typeof AuthenticatedCommunicationAuditCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coding-concepts/upload': {
      id: '/_authenticated/coding-concepts/upload'
      path: '/coding-concepts/upload'
      fullPath: '/coding-concepts/upload'
      preLoaderRoute: typeof AuthenticatedCodingConceptsUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coding-concepts/search': {
      id: '/_authenticated/coding-concepts/search'
      path: '/coding-concepts/search'
      fullPath: '/coding-concepts/search'
      preLoaderRoute: typeof AuthenticatedCodingConceptsSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coding-concepts/match': {
      id: '/_authenticated/coding-concepts/match'
      path: '/coding-concepts/match'
      fullPath: '/coding-concepts/match'
      preLoaderRoute: typeof AuthenticatedCodingConceptsMatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/uoms/$uomId/edit': {
      id: '/_authenticated/uoms/$uomId/edit'
      path: '/edit'
      fullPath: '/uoms/$uomId/edit'
      preLoaderRoute: typeof AuthenticatedUomsUomIdEditRouteImport
      parentRoute: typeof AuthenticatedUomsUomIdRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedUomsUomIdRouteChildren {
  AuthenticatedUomsUomIdEditRoute: typeof AuthenticatedUomsUomIdEditRoute
}

const AuthenticatedUomsUomIdRouteChildren: AuthenticatedUomsUomIdRouteChildren =
  {
    AuthenticatedUomsUomIdEditRoute: AuthenticatedUomsUomIdEditRoute,
  }

const AuthenticatedUomsUomIdRouteWithChildren =
  AuthenticatedUomsUomIdRoute._addFileChildren(
    AuthenticatedUomsUomIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAesRouteRoute: typeof AuthenticatedAesRouteRoute
  AuthenticatedBroadcastsRouteRoute: typeof AuthenticatedBroadcastsRouteRoute
  AuthenticatedCommunicationChannelsRouteRoute: typeof AuthenticatedCommunicationChannelsRouteRoute
  AuthenticatedMappingRouteRoute: typeof AuthenticatedMappingRouteRoute
  AuthenticatedMessageLogsRouteRoute: typeof AuthenticatedMessageLogsRouteRoute
  AuthenticatedMessageTemplatesRouteRoute: typeof AuthenticatedMessageTemplatesRouteRoute
  AuthenticatedMessagesRouteRoute: typeof AuthenticatedMessagesRouteRoute
  AuthenticatedNotificationTemplatesRouteRoute: typeof AuthenticatedNotificationTemplatesRouteRoute
  AuthenticatedNotificationsRouteRoute: typeof AuthenticatedNotificationsRouteRoute
  AuthenticatedRoutingRouteRoute: typeof AuthenticatedRoutingRouteRoute
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedCodingConceptsMatchRoute: typeof AuthenticatedCodingConceptsMatchRoute
  AuthenticatedCodingConceptsSearchRoute: typeof AuthenticatedCodingConceptsSearchRoute
  AuthenticatedCodingConceptsUploadRoute: typeof AuthenticatedCodingConceptsUploadRoute
  AuthenticatedCommunicationAuditCenterRoute: typeof AuthenticatedCommunicationAuditCenterRoute
  AuthenticatedCommunicationFlowGraphRoute: typeof AuthenticatedCommunicationFlowGraphRoute
  AuthenticatedCommunicationMessageTesterRoute: typeof AuthenticatedCommunicationMessageTesterRoute
  AuthenticatedCommunicationTraceExplorerRoute: typeof AuthenticatedCommunicationTraceExplorerRoute
  AuthenticatedLisResourceKeyRoute: typeof AuthenticatedLisResourceKeyRoute
  AuthenticatedProductsProductIdRoute: typeof AuthenticatedProductsProductIdRoute
  AuthenticatedUomsUomIdRoute: typeof AuthenticatedUomsUomIdRouteWithChildren
  AuthenticatedAuditLogsIndexRoute: typeof AuthenticatedAuditLogsIndexRoute
  AuthenticatedBranchesIndexRoute: typeof AuthenticatedBranchesIndexRoute
  AuthenticatedCategoriesIndexRoute: typeof AuthenticatedCategoriesIndexRoute
  AuthenticatedChannelsIndexRoute: typeof AuthenticatedChannelsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedCodingConceptsIndexRoute: typeof AuthenticatedCodingConceptsIndexRoute
  AuthenticatedConversationsIndexRoute: typeof AuthenticatedConversationsIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDrugComponentsIndexRoute: typeof AuthenticatedDrugComponentsIndexRoute
  AuthenticatedExchangesIndexRoute: typeof AuthenticatedExchangesIndexRoute
  AuthenticatedInventoryIndexRoute: typeof AuthenticatedInventoryIndexRoute
  AuthenticatedJournalEntriesIndexRoute: typeof AuthenticatedJournalEntriesIndexRoute
  AuthenticatedJournalEntryLinesIndexRoute: typeof AuthenticatedJournalEntryLinesIndexRoute
  AuthenticatedJournalsIndexRoute: typeof AuthenticatedJournalsIndexRoute
  AuthenticatedLisIndexRoute: typeof AuthenticatedLisIndexRoute
  AuthenticatedManufacturersIndexRoute: typeof AuthenticatedManufacturersIndexRoute
  AuthenticatedOrganizationsIndexRoute: typeof AuthenticatedOrganizationsIndexRoute
  AuthenticatedParticipantsIndexRoute: typeof AuthenticatedParticipantsIndexRoute
  AuthenticatedPaymentMethodsIndexRoute: typeof AuthenticatedPaymentMethodsIndexRoute
  AuthenticatedPharmaceuticsIndexRoute: typeof AuthenticatedPharmaceuticsIndexRoute
  AuthenticatedPriceListItemsIndexRoute: typeof AuthenticatedPriceListItemsIndexRoute
  AuthenticatedPriceListsIndexRoute: typeof AuthenticatedPriceListsIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedPurchasesIndexRoute: typeof AuthenticatedPurchasesIndexRoute
  AuthenticatedQuestionnairesIndexRoute: typeof AuthenticatedQuestionnairesIndexRoute
  AuthenticatedQuestionsIndexRoute: typeof AuthenticatedQuestionsIndexRoute
  AuthenticatedReceivablesIndexRoute: typeof AuthenticatedReceivablesIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedRolesIndexRoute: typeof AuthenticatedRolesIndexRoute
  AuthenticatedSalesIndexRoute: typeof AuthenticatedSalesIndexRoute
  AuthenticatedStockLocationsIndexRoute: typeof AuthenticatedStockLocationsIndexRoute
  AuthenticatedSuppliersIndexRoute: typeof AuthenticatedSuppliersIndexRoute
  AuthenticatedUomsIndexRoute: typeof AuthenticatedUomsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedWorkflowConfigurationIndexRoute: typeof AuthenticatedWorkflowConfigurationIndexRoute
  AuthenticatedWorkflowEventsIndexRoute: typeof AuthenticatedWorkflowEventsIndexRoute
  AuthenticatedWorkflowInstancesIndexRoute: typeof AuthenticatedWorkflowInstancesIndexRoute
  AuthenticatedWorkflowsIndexRoute: typeof AuthenticatedWorkflowsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAesRouteRoute: AuthenticatedAesRouteRoute,
  AuthenticatedBroadcastsRouteRoute: AuthenticatedBroadcastsRouteRoute,
  AuthenticatedCommunicationChannelsRouteRoute:
    AuthenticatedCommunicationChannelsRouteRoute,
  AuthenticatedMappingRouteRoute: AuthenticatedMappingRouteRoute,
  AuthenticatedMessageLogsRouteRoute: AuthenticatedMessageLogsRouteRoute,
  AuthenticatedMessageTemplatesRouteRoute:
    AuthenticatedMessageTemplatesRouteRoute,
  AuthenticatedMessagesRouteRoute: AuthenticatedMessagesRouteRoute,
  AuthenticatedNotificationTemplatesRouteRoute:
    AuthenticatedNotificationTemplatesRouteRoute,
  AuthenticatedNotificationsRouteRoute: AuthenticatedNotificationsRouteRoute,
  AuthenticatedRoutingRouteRoute: AuthenticatedRoutingRouteRoute,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedCodingConceptsMatchRoute: AuthenticatedCodingConceptsMatchRoute,
  AuthenticatedCodingConceptsSearchRoute:
    AuthenticatedCodingConceptsSearchRoute,
  AuthenticatedCodingConceptsUploadRoute:
    AuthenticatedCodingConceptsUploadRoute,
  AuthenticatedCommunicationAuditCenterRoute:
    AuthenticatedCommunicationAuditCenterRoute,
  AuthenticatedCommunicationFlowGraphRoute:
    AuthenticatedCommunicationFlowGraphRoute,
  AuthenticatedCommunicationMessageTesterRoute:
    AuthenticatedCommunicationMessageTesterRoute,
  AuthenticatedCommunicationTraceExplorerRoute:
    AuthenticatedCommunicationTraceExplorerRoute,
  AuthenticatedLisResourceKeyRoute: AuthenticatedLisResourceKeyRoute,
  AuthenticatedProductsProductIdRoute: AuthenticatedProductsProductIdRoute,
  AuthenticatedUomsUomIdRoute: AuthenticatedUomsUomIdRouteWithChildren,
  AuthenticatedAuditLogsIndexRoute: AuthenticatedAuditLogsIndexRoute,
  AuthenticatedBranchesIndexRoute: AuthenticatedBranchesIndexRoute,
  AuthenticatedCategoriesIndexRoute: AuthenticatedCategoriesIndexRoute,
  AuthenticatedChannelsIndexRoute: AuthenticatedChannelsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedCodingConceptsIndexRoute: AuthenticatedCodingConceptsIndexRoute,
  AuthenticatedConversationsIndexRoute: AuthenticatedConversationsIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDrugComponentsIndexRoute: AuthenticatedDrugComponentsIndexRoute,
  AuthenticatedExchangesIndexRoute: AuthenticatedExchangesIndexRoute,
  AuthenticatedInventoryIndexRoute: AuthenticatedInventoryIndexRoute,
  AuthenticatedJournalEntriesIndexRoute: AuthenticatedJournalEntriesIndexRoute,
  AuthenticatedJournalEntryLinesIndexRoute:
    AuthenticatedJournalEntryLinesIndexRoute,
  AuthenticatedJournalsIndexRoute: AuthenticatedJournalsIndexRoute,
  AuthenticatedLisIndexRoute: AuthenticatedLisIndexRoute,
  AuthenticatedManufacturersIndexRoute: AuthenticatedManufacturersIndexRoute,
  AuthenticatedOrganizationsIndexRoute: AuthenticatedOrganizationsIndexRoute,
  AuthenticatedParticipantsIndexRoute: AuthenticatedParticipantsIndexRoute,
  AuthenticatedPaymentMethodsIndexRoute: AuthenticatedPaymentMethodsIndexRoute,
  AuthenticatedPharmaceuticsIndexRoute: AuthenticatedPharmaceuticsIndexRoute,
  AuthenticatedPriceListItemsIndexRoute: AuthenticatedPriceListItemsIndexRoute,
  AuthenticatedPriceListsIndexRoute: AuthenticatedPriceListsIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedPurchasesIndexRoute: AuthenticatedPurchasesIndexRoute,
  AuthenticatedQuestionnairesIndexRoute: AuthenticatedQuestionnairesIndexRoute,
  AuthenticatedQuestionsIndexRoute: AuthenticatedQuestionsIndexRoute,
  AuthenticatedReceivablesIndexRoute: AuthenticatedReceivablesIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedRolesIndexRoute: AuthenticatedRolesIndexRoute,
  AuthenticatedSalesIndexRoute: AuthenticatedSalesIndexRoute,
  AuthenticatedStockLocationsIndexRoute: AuthenticatedStockLocationsIndexRoute,
  AuthenticatedSuppliersIndexRoute: AuthenticatedSuppliersIndexRoute,
  AuthenticatedUomsIndexRoute: AuthenticatedUomsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedWorkflowConfigurationIndexRoute:
    AuthenticatedWorkflowConfigurationIndexRoute,
  AuthenticatedWorkflowEventsIndexRoute: AuthenticatedWorkflowEventsIndexRoute,
  AuthenticatedWorkflowInstancesIndexRoute:
    AuthenticatedWorkflowInstancesIndexRoute,
  AuthenticatedWorkflowsIndexRoute: AuthenticatedWorkflowsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRoute
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRoute,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  DamorexIndexRoute: DamorexIndexRoute,
  QuestionnaireIndexRoute: QuestionnaireIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
